### ISSUE TITLE
haxe.Template  sample fails with DCE

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/HaxeManual#475]
Hej !

```haxe
class Main {
  static function main() {
    new Main();
  }

  public function new() {
    var user = {name: "Mark", distance: 3500};
    var sample = "The results: $$display(::user::,::time::)";
    var template = new haxe.Template(sample);
    var output = template.execute({user: user, time: 15}, this);
    trace(output);
  }

  function display(resolve:String->Dynamic, user:User, time:Int) {
    return user.name + " ran " + (user.distance / 1000) + " kilometers in " +
      time + " minutes";
  }
}

typedef User = {name:String, distance:Int}
```

This sample https://haxe.org/manual/std-template.html fails in PHP 7 with Haxe Compiler 4.2.0-rc.1+5145ddb
Error : 
```haxe
Fatal error:  Uncaught Macro call display(<function>,{ name : Mark, distance : 3500 },15) failed (ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /lib/Reflect.php:37
Stack trace:
#0 /lib/Reflect.php(37): php\Boot::php\{closure}(2, 'call_user_func_...', '/www/o...', 37, Array)
HaxeFoundation/haxe#1 /lib/haxe/Template.php(916): Reflect::callMethod(Object(Server), NULL, Object(Array_hx))
HaxeFoundation/haxe#2 /lib/haxe/Template.php(826): haxe\Template-&gt;run(Object(haxe\_Template\TemplateExpr))
HaxeFoundation/haxe#3 /lib/haxe/Template.php(127): haxe\Template-&gt;run(Object(haxe\_Template\TemplateExpr))
HaxeFoundation/haxe#4 /lib/Server.php(163): haxe\Template-&gt;execute(Object(_HxAnon_Server4), Object(Server))
HaxeFoundation/haxe#5 /lib/Server.php(42): Server-&gt;__construct()
HaxeFoundation/haxe#6 /www/index.php(14): Server::main()
HaxeFoundation/haxe#7 {main})
  thrown in /lib/haxe/Exception.php on line 96
```

**Comment by filt3rek** [comment]
Thanks for your answer Aleksandr.

I've dig a bit and it gives null here : https://github.com/HaxeFoundation/haxe/blob/7928a8634cdbc70eded923ebc2a0b652340dfa6b/std/php/_std/Reflect.hx#L49
When it's called here : https://github.com/HaxeFoundation/haxe/blob/7928a8634cdbc70eded923ebc2a0b652340dfa6b/std/haxe/Template.hx#L481

**Comment by filt3rek** [comment]
Ok, yes It's linked to DCE, so the class method must have `@:keep` meta. 
And I didn't knew closures can also have `@:keep` meta. It runs well now.
Thanks
